name: CD MQTT y Main API

on:
  push:
    branches:
      - "main"
      - "feat/cd_build_locally"
  workflow_dispatch:

jobs:
  build-and-push-mqtt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup environment variables
        run: |
          echo "TIMESTAMP=$(date +"%Y-%d-%m_%H-%M-%S")" >> $GITHUB_ENV

          cp ./template.env .env
          echo "IP_INFO_TOKEN=${{ secrets.IP_INFO_TOKEN }}" >> .env
          echo "CURRENCY_CONVERSION_KEY=${{ secrets.CURRENCY_CONVERSION_KEY }}" >> .env
          echo "AWS_ACCESS_KEY_S3=${{ secrets.AWS_ACCESS_KEY_S3 }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY_S3=${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "MQTT_BROKER_USERNAME=${{ secrets.MQTT_BROKER_USERNAME }}" >> .env
          echo "MQTT_BROKER_PASSWORD=${{ secrets.MQTT_BROKER_PASSWORD }}" >> .env
          echo "CLOUDFLARE_API_KEY=${{ secrets.CLOUDFLARE_API_KEY }}" >> .env

      - name: Install docker
        run: |
          echo "deb [arch=$(dpkg --print-architecture) trusted=true] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Build MQTT Image
        run: |
          sudo chmod -R a+x ./
          sudo docker compose -f ./docker-compose.production.yaml build mqtt

      - name: Tag image
        run: |
          sudo docker tag grupo19-backend-mqtt registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/mqtt:github-${TIMESTAMP}
          sudo docker tag grupo19-backend-mqtt registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/mqtt:latest
          sudo docker tag grupo19-backend-mqtt registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/mqtt:github-latest

      - name: Push image
        run: |
          sudo docker push registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/mqtt:latest
          sudo docker push registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/mqtt:github-latest
          sudo docker push registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/mqtt:github-${TIMESTAMP}

  build-and-push-main-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup environment variables
        run: |
          echo "TIMESTAMP=$(date +"%Y-%d-%m_%H-%M-%S")" >> $GITHUB_ENV

          cp ./template.env .env
          echo "IP_INFO_TOKEN=${{ secrets.IP_INFO_TOKEN }}" >> .env
          echo "CURRENCY_CONVERSION_KEY=${{ secrets.CURRENCY_CONVERSION_KEY }}" >> .env
          echo "AWS_ACCESS_KEY_S3=${{ secrets.AWS_ACCESS_KEY_S3 }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY_S3=${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "MQTT_BROKER_USERNAME=${{ secrets.MQTT_BROKER_USERNAME }}" >> .env
          echo "MQTT_BROKER_PASSWORD=${{ secrets.MQTT_BROKER_PASSWORD }}" >> .env
          echo "CLOUDFLARE_API_KEY=${{ secrets.CLOUDFLARE_API_KEY }}" >> .env

      - name: Install docker
        run: |
          echo "deb [arch=$(dpkg --print-architecture) trusted=true] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Build Main API Image
        run: |
          sudo chmod -R a+x ./
          sudo docker compose -f ./docker-compose.production.yaml build api

      - name: Tag image
        run: |
          sudo docker tag grupo19-backend-api registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/main-api:github-${TIMESTAMP}
          sudo docker tag grupo19-backend-api registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/main-api:github-latest
          sudo docker tag grupo19-backend-api registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/main-api:latest

      - name: Push image
        run: |
          sudo docker push registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/main-api:latest
          sudo docker push registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/main-api:github-latest
          sudo docker push registry.docker.ljgonzalez.cl/arqui-sis/async-tech/backend/main-api:github-${TIMESTAMP}

  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Install ssh
        run: sudo apt-get install openssh-client sshpass -y

      - name: Setup environment variables
        run: |
          echo "EC2HOST=arqui.ljg.cl" >> $GITHUB_ENV
          echo "EC2PORT=22" >> $GITHUB_ENV
          echo "EC2USER=ubuntu" >> $GITHUB_ENV
          echo "EC2PASSWD=${{ secrets.EC2PASSWD }}" >> $GITHUB_ENV

      - name: Take containers down
        id: take-stack-down
        run: |
          connect_ssh() { sshpass -p "${EC2PASSWD}" ssh -o StrictHostKeyChecking=no -p ${EC2PORT} ${EC2USER}@${EC2HOST} -Ct " cd /home/ubuntu/backend && $@" ; }
          connect_ssh "sudo docker compose -f ./docker-compose.production.yaml down"

      - name: FAILURE - Raise containers back up
        if: failure() && steps.take-stack-down.outcome == 'failure'
        run: |
          connect_ssh() { sshpass -p "${EC2PASSWD}" ssh -o StrictHostKeyChecking=no -p ${EC2PORT} ${EC2USER}@${EC2HOST} -Ct " cd /home/ubuntu/backend && $@" ; }
          connect_ssh "sudo docker compose -f ./docker-compose.production.yaml up -d"
          exit 1

      - name: Update repo
        run: |
          connect_ssh() { sshpass -p "${EC2PASSWD}" ssh -o StrictHostKeyChecking=no -p ${EC2PORT} ${EC2USER}@${EC2HOST} -Ct " cd /home/ubuntu/backend && $@" ; }
          connect_ssh "git fetch"
          #connect_ssh "git reset --hard && git checkout main && git pull "
          connect_ssh "git reset --hard && git checkout feat/cd_build_locally && git pull "

  update_ssl-certificates:
    needs:
      - update-repo

    runs-on: ubuntu-latest

    steps:
      - name: Setup environment variables
        run: |
          echo "EC2HOST=arqui.ljg.cl" >> $GITHUB_ENV
          echo "EC2PORT=22" >> $GITHUB_ENV
          echo "EC2USER=ubuntu" >> $GITHUB_ENV
          echo "EC2PASSWD=${{ secrets.EC2PASSWD }}" >> $GITHUB_ENV
          
          cp ./template.env .env
          echo "IP_INFO_TOKEN=${{ secrets.IP_INFO_TOKEN }}" >> .env
          echo "CURRENCY_CONVERSION_KEY=${{ secrets.CURRENCY_CONVERSION_KEY }}" >> .env
          echo "AWS_ACCESS_KEY_S3=${{ secrets.AWS_ACCESS_KEY_S3 }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY_S3=${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "MQTT_BROKER_USERNAME=${{ secrets.MQTT_BROKER_USERNAME }}" >> .env
          echo "MQTT_BROKER_PASSWORD=${{ secrets.MQTT_BROKER_PASSWORD }}" >> .env
          echo "CLOUDFLARE_API_KEY=${{ secrets.CLOUDFLARE_API_KEY }}" >> .env

      - name: Save .env
        run: |
          sshpass -p "${EC2PASSWD}" scp -o StrictHostKeyChecking=no -p ${EC2PORT} ./.env ${EC2USER}@${EC2HOST}:/home/${EC2USER}/backend/

      - name: Save SSL Certificates
        run: |
          sshpass -p "${EC2PASSWD}" scp -o StrictHostKeyChecking=no -p ${EC2PORT} ./nginx/templates/letsencrypt/arqui.ljg.cl/* ${EC2USER}@${EC2HOST}:/home/${EC2USER}/backend/nginx/templates/letsencrypt/arqui.ljg.cl/

  update-and-reload-containers:
    needs:
      - build-and-push-mqtt
      - build-and-push-main-api
      - update_ssl-certificates
    runs-on: ubuntu-latest

    steps:
    - name: Install ssh
      run: sudo apt-get install openssh-client sshpass -y

    - name: Setup environment variables
      run: |
        echo "EC2HOST=arqui.ljg.cl" >> $GITHUB_ENV
        echo "EC2PORT=22" >> $GITHUB_ENV
        echo "EC2USER=ubuntu" >> $GITHUB_ENV
        echo "EC2PASSWD=${{ secrets.EC2PASSWD }}" >> $GITHUB_ENV

    - name: Update and reload containers
      run: |
        connect_ssh() { sshpass -p "${EC2PASSWD}" ssh -o StrictHostKeyChecking=no -p ${EC2PORT} ${EC2USER}@${EC2HOST} -Ct " cd /home/ubuntu/backend && $@" ; }
        connect_ssh "sudo docker system prune -a -f" ;
        connect_ssh "sudo docker compose pull" ;
        connect_ssh "sudo docker compose -f ./docker-compose.production.yaml up -d" ;

  backup-containers:
    needs:
      - update-and-reload-containers
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Setup environment variables
        run: |
          echo "EC2HOST=arqui.ljg.cl" >> $GITHUB_ENV
          echo "EC2PORT=22" >> $GITHUB_ENV
          echo "EC2USER=ubuntu" >> $GITHUB_ENV
          echo "EC2PASSWD=${{ secrets.EC2PASSWD }}" >> $GITHUB_ENV

      - name: FAILURE - Raise containers back up on old checkout
        run:
          sudo apt-get install openssh-client sshpass -y ;

          connect_ssh() { sshpass -p "${EC2PASSWD}" ssh -o StrictHostKeyChecking=no -p ${EC2PORT} ${EC2USER}@${EC2HOST} -Ct " cd /home/ubuntu/backend && $@" ; }
          
          connect_ssh "git reset --hard && git checkout f5d6b2a6 " ;
          connect_ssh "sudo docker compose -f ./docker-compose.production.yaml down" ;
          connect_ssh "sudo docker system prune -a -f" ;
          connect_ssh "sudo docker compose -f ./docker-compose.production.yaml build --no-cache" ;
          connect_ssh "sudo docker compose -f ./docker-compose.production.yaml pull" ;
          connect_ssh "sudo docker compose -f ./docker-compose.production.yaml up -d" ;
